services:
  client:
    build:
      context: client
    ports:
      - "5173:5173"
    networks:
      - mern-net

  backend:
    build:
      context: server
    ports:
      - "5000:5000"
    networks:
      - mern-net

networks:
  mern-net: {}